"""Balchar sprite definitions — idle, walk, jump animations.

24x32 pixels per frame. Balearic foner (slinger).

Character design (matching reference):
- White headwrap/turban
- Deep orange-tan skin (Balearic)
- Open white tunic (V-neck showing chest)
- Bright red sash at waist (most distinctive feature)
- Leather arm bracers
- Dark brown pants
- Brown leather boots
- Sling with dangling cord in left hand

Feet anchored at the bottom of the grid (row 31) so the character
sits flush on platforms.

MIRROR = True: sprites are drawn facing left, mirrored to face right
at generation time.
"""

from tools.sprite_defs.palettes import BALCHAR_PALETTE

PALETTE = BALCHAR_PALETTE
WIDTH = 24
HEIGHT = 32
MIRROR = True

# fmt: off

_FRAME_NEUTRAL = """
    ........................
    ........wwwwww..........
    .......wWWWWWWw.........
    ......wwWWWWWWww........
    ......wWWWWWWWWw........
    ......wssssssssw........
    ......seEssssEes........
    ......ssssssssss........
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    .....TttttttttC.........
    .....Tttsssttcc.........
    ....atttssttttcA........
    ....atttttttttcA........
    .....slttttttttc........
    .....l.cccccccc.........
    ....lL.cccccccc.........
    .....RrrrrrrrrR.........
    ......xrrrrrrx..........
    ......pppppppp..........
    ......pPppppPp..........
    ......pppppppp..........
    .......pp..pp...........
    .......pp..pp...........
    .......pp..pp...........
    .......qq..qq...........
    .......bb..bb...........
    .......bB..bB...........
    .......nb..nb...........
    ......nbb..bbn..........
    ........................
    """

IDLE = [
    # Frame 0: neutral stance
    _FRAME_NEUTRAL,
    # Frame 1: breathing in — torso up 1px (neck row removed, extra pants row)
    """
    ........................
    ........wwwwww..........
    .......wWWWWWWw.........
    ......wwWWWWWWww........
    ......wWWWWWWWWw........
    ......wssssssssw........
    ......seEssssEes........
    ......ssssssssss........
    ......ssssmmssss........
    .......ssssssss.........
    .....TttttttttC.........
    .....Tttsssttcc.........
    ....atttssttttcA........
    ....atttttttttcA........
    .....slttttttttc........
    .....l.cccccccc.........
    ....lL.cccccccc.........
    .....RrrrrrrrrR.........
    ......xrrrrrrx..........
    ......pppppppp..........
    ......pPppppPp..........
    ......pppppppp..........
    ......pppppppp..........
    .......pp..pp...........
    .......pp..pp...........
    .......pp..pp...........
    .......qq..qq...........
    .......bb..bb...........
    .......bB..bB...........
    .......nb..nb...........
    ......nbb..bbn..........
    ........................
    """,
    # Frame 2: same as frame 0
    _FRAME_NEUTRAL,
    # Frame 3: breathing out — shoulders drop (extra neck row, fewer pants rows)
    """
    ........................
    ........wwwwww..........
    .......wWWWWWWw.........
    ......wwWWWWWWww........
    ......wWWWWWWWWw........
    ......wssssssssw........
    ......seEssssEes........
    ......ssssssssss........
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    .......ssssss...........
    .....TttttttttC.........
    .....Tttsssttcc.........
    ....atttssttttcA........
    ....atttttttttcA........
    .....slttttttttc........
    .....l.cccccccc.........
    ....lL.cccccccc.........
    .....RrrrrrrrrR.........
    ......xrrrrrrx..........
    ......pppppppp..........
    ......pppppppp..........
    .......pp..pp...........
    .......pp..pp...........
    .......pp..pp...........
    .......qq..qq...........
    .......bb..bb...........
    .......bB..bB...........
    .......nb..nb...........
    ......nbb..bbn..........
    ........................
    """,
]

# Placeholder animations — use neutral frame until redesigned with new palette.
WALK = [_FRAME_NEUTRAL] * 6
JUMP = [_FRAME_NEUTRAL] * 2
WALL_SLIDE = [_FRAME_NEUTRAL] * 2
WALL_JUMP = [_FRAME_NEUTRAL] * 2

# fmt: on

ANIMATIONS = {
    "idle": IDLE,
    "walk": WALK,
    "jump": JUMP,
    "wall_slide": WALL_SLIDE,
    "wall_jump": WALL_JUMP,
}
