"""Bep sprite definitions — idle animation.

16x16 pixels per frame. Small, round myotragus companion.
Palette keys reference BEP_PALETTE in palettes.py.

Each frame is a multiline string. The generator strips and pads rows.

Design notes:
- Round, compact body (myotragus were small, stocky)
- Prominent eyes for expressiveness
- Tiny curved horns
- Short legs with hooves
- Vertical bob animation handled by game code; frames show ear/tail twitch
"""

from tools.sprite_defs.palettes import BEP_PALETTE

PALETTE = BEP_PALETTE
WIDTH = 24
HEIGHT = 24

# fmt: off

IDLE = [
    # Frame 0: neutral, ears up
    """
    ................
    ..h...h.........
    ..hf.fh.........
    .fffffffff......
    .fFFFFFFFf......
    .feEffeEff......
    .fffnffff.......
    .fffffffff......
    ..fFFFFFF.......
    ..ffffffff......
    ..gffffffg......
    ..ggffffgg......
    ...bf..fb.......
    ...bf..fb.......
    ................
    ................
    """,
    # Frame 1: ear twitch (left ear down)
    """
    ................
    ......h.........
    ..hf.fh.........
    .fffffffff......
    .fFFFFFFFf......
    .feEffeEff......
    .fffnffff.......
    .fffffffff......
    ..fFFFFFF.......
    ..ffffffff......
    ..gffffffg......
    ..ggffffgg......
    ...bf..fb.......
    ...bf..fb.......
    ................
    ................
    """,
    # Frame 2: neutral (same as 0)
    """
    ................
    ..h...h.........
    ..hf.fh.........
    .fffffffff......
    .fFFFFFFFf......
    .feEffeEff......
    .fffnffff.......
    .fffffffff......
    ..fFFFFFF.......
    ..ffffffff......
    ..gffffffg......
    ..ggffffgg......
    ...bf..fb.......
    ...bf..fb.......
    ................
    ................
    """,
    # Frame 3: blink (eyes closed)
    """
    ................
    ..h...h.........
    ..hf.fh.........
    .fffffffff......
    .fFFFFFFFf......
    .fggffggff......
    .fffnffff.......
    .fffffffff......
    ..fFFFFFF.......
    ..ffffffff......
    ..gffffffg......
    ..ggffffgg......
    ...bf..fb.......
    ...bf..fb.......
    ................
    ................
    """,
]

# fmt: on

ANIMATIONS = {
    "idle": IDLE,
}
