"""Breakable object sprite definitions — pot and crate.

16x16 pixels per frame. Static sprites for destructible objects.
"""

from tools.sprite_defs.palettes import BREAKABLE_POT_PALETTE, BREAKABLE_CRATE_PALETTE

# ── Pot ──────────────────────────────────────────────────────

POT_W = 24
POT_H = 24

POT_PALETTE_MAP = BREAKABLE_POT_PALETTE

POT = [
    """
    ................
    .....rRRRr......
    ....rRRRRRr.....
    ....RRRRRRR.....
    ...DpppppppD....
    ...dpPPPPPpd....
    ..ddpPPPPPpdd...
    ..ddpPPPPPpdd...
    ..ddpPPPPPpdd...
    ..ddpPPPPPpdd...
    ...dpPPPPPpd....
    ...dpPPPPPpd....
    ...ddpppppdd....
    ....ddDDDdd.....
    .....ddddd......
    ................
    """,
]

# ── Crate ────────────────────────────────────────────────────

CRATE_W = 24
CRATE_H = 24

CRATE_PALETTE_MAP = BREAKABLE_CRATE_PALETTE

CRATE = [
    """
    ................
    .DDDDDDDDDDDDd..
    .DwwwwwwwwwwDd..
    .DwWWwwwwWWwDd..
    .DwwWWwwWWwwDd..
    .DwwwWWWWwwwDd..
    .DwwwwnwwwwwDd..
    .DwwwWWWWwwwDd..
    .DwwWWwwWWwwDd..
    .DwWWwwwwWWwDd..
    .DwwwwwwwwwwDd..
    .DwwwwwwwwwwDd..
    .DDDDDDDDDDDDd..
    ..dddddddddddd..
    ................
    ................
    """,
]
