"""Pickup sprite definitions — heart and stone.

12x12 pixels per frame. Simple, readable sprites for collectibles.
"""

from tools.sprite_defs.palettes import HEART_PALETTE, STONE_PICKUP_PALETTE

# ── Heart Pickup ─────────────────────────────────────────────

HEART_W = 12
HEART_H = 12

HEART_PALETTE_MAP = HEART_PALETTE

HEART = [
    """
    .rr...rr....
    rRRr.rRRr...
    rRwRrrRRRr..
    rRRRRRRRRr..
    rRRRRRRRRr..
    .rRRRRRRr...
    ..rRRRRr....
    ...rRRr.....
    ....rr......
    ............
    ............
    ............
    """,
]

# ── Stone Pickup ─────────────────────────────────────────────

STONE_W = 12
STONE_H = 12

STONE_PALETTE_MAP = STONE_PICKUP_PALETTE

STONE = [
    """
    ............
    ....ddd.....
    ...dsSsd....
    ..dsShSsd...
    ..sSSSSSd...
    ..sSSSSsd...
    ..dsSSSsd...
    ...dssSd....
    ....ddd.....
    ............
    ............
    ............
    """,
]
