"""Possessed Sheep sprite definitions — idle, walk animations.

16x16 pixels per frame. Round woolly sheep with red possessed eyes.

The sheep has a fluffy oval body, four stubby legs, small curled
horns, and glowing red eyes from the possession curse.
"""

from tools.sprite_defs.palettes import POSSESSED_SHEEP_PALETTE

PALETTE = POSSESSED_SHEEP_PALETTE
WIDTH = 24
HEIGHT = 24

# fmt: off

IDLE = [
    # Frame 0: neutral stance
    """
    ......HH........
    ....wwwwww......
    ...wwwWwwww.....
    ..wwwwwwwwww....
    ..wfffffffww....
    ..wfeEffeEfw....
    ..wfffffffww....
    ...wwwwwwww.....
    ..wwwWwWwwww....
    ..dwwwwwwwwd....
    ..ddwwwwwwdd....
    ...hh....hh.....
    ...hh....hh.....
    ................
    ................
    ................
    """,
    # Frame 1: eyes pulse brighter
    """
    ......HH........
    ....wwwwww......
    ...wwwWwwww.....
    ..wwwwwwwwww....
    ..wfffffffww....
    ..wfEEffEEfw....
    ..wfffffffww....
    ...wwwwwwww.....
    ..wwwWwWwwww....
    ..dwwwwwwwwd....
    ..ddwwwwwwdd....
    ...hh....hh.....
    ...hh....hh.....
    ................
    ................
    ................
    """,
]

WALK = [
    # Frame 0: right legs forward
    """
    ......HH........
    ....wwwwww......
    ...wwwWwwww.....
    ..wwwwwwwwww....
    ..wfffffffww....
    ..wfeEffeEfw....
    ..wfffffffww....
    ...wwwwwwww.....
    ..wwwWwWwwww....
    ..dwwwwwwwwd....
    ..ddwwwwwwdd....
    ..hh......hh....
    ..hh......hh....
    ................
    ................
    ................
    """,
    # Frame 1: passing — legs together, body up 1px
    """
    ................
    ......HH........
    ....wwwwww......
    ...wwwWwwww.....
    ..wwwwwwwwww....
    ..wfffffffww....
    ..wfeEffeEfw....
    ..wfffffffww....
    ...wwwwwwww.....
    ..wwwWwWwwww....
    ..dwwwwwwwwd....
    ..ddwwwwwwdd....
    ...hh....hh.....
    ...hh....hh.....
    ................
    ................
    """,
    # Frame 2: left legs forward
    """
    ......HH........
    ....wwwwww......
    ...wwwWwwww.....
    ..wwwwwwwwww....
    ..wfffffffww....
    ..wfeEffeEfw....
    ..wfffffffww....
    ...wwwwwwww.....
    ..wwwWwWwwww....
    ..dwwwwwwwwd....
    ..ddwwwwwwdd....
    ....hh..hh......
    ....hh..hh......
    ................
    ................
    ................
    """,
    # Frame 3: passing — legs together, body up 1px
    """
    ................
    ......HH........
    ....wwwwww......
    ...wwwWwwww.....
    ..wwwwwwwwww....
    ..wfffffffww....
    ..wfEEffEEfw....
    ..wfffffffww....
    ...wwwwwwww.....
    ..wwwWwWwwww....
    ..dwwwwwwwwd....
    ..ddwwwwwwdd....
    ...hh....hh.....
    ...hh....hh.....
    ................
    ................
    """,
]

# fmt: on

ANIMATIONS = {
    "idle": IDLE,
    "walk": WALK,
}
