"""Ramon sprite definitions — idle, walk, jump animations.

24x32 pixels per frame. Balearic foner (slinger).

Character design:
- Deeply tanned, stocky build
- BIG head (chibi proportions for charm)
- Medium-length dark hair swept BACKWARDS, held by sling-headband
  (not falling on shoulders — just enough to need the band)
- Knee-length white/cream robe
- Second sling as belt with dangling end
- Tanned legs visible below robe, leather sandals
- Simple determined face

Feet anchored at the bottom of the grid (row 31) so the character
sits flush on platforms. Character maximizes vertical space.

MIRROR = True: sprites are drawn facing left, mirrored to face right
at generation time. Game flips back when facing_right=False.
"""

from tools.sprite_defs.palettes import RAMON_PALETTE

PALETTE = RAMON_PALETTE
WIDTH = 24
HEIGHT = 32
MIRROR = True

# fmt: off

IDLE = [
    # Frame 0: neutral stance — feet grounded at bottom
    """
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    .....Lrrrrrrrrl.........
    ....LrRRrrrrRRrl........
    ....LrrrrrrrrrrrL.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......cccccccccc........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......GG....GG.........
    .......dd....dd.........
    .......dD....Dd.........
    """,
    # Frame 1: breathing in — torso up 1px (neck row gone)
    """
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    .....Lrrrrrrrrl.........
    ....LrRRrrrrRRrl........
    ....LrrrrrrrrrrrL.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......cccccccccc........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......GG....GG.........
    .......dd....dd.........
    .......dD....Dd.........
    """,
    # Frame 2: same as frame 0
    """
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    .....Lrrrrrrrrl.........
    ....LrRRrrrrRRrl........
    ....LrrrrrrrrrrrL.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......cccccccccc........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......GG....GG.........
    .......dd....dd.........
    .......dD....Dd.........
    """,
    # Frame 3: breathing out — shoulders drop (extra neck row, robe compresses)
    """
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    .........ss.............
    .....Lrrrrrrrrl.........
    ....LrRRrrrrRRrl........
    ....LrrrrrrrrrrrL.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......cccccccccc........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......GG....GG.........
    .......dd....dd.........
    .......dD....Dd.........
    """,
]


# 6-frame walk cycle. Legs alternate, 1px body bob on passing frames.
# Robe sways slightly. Hair bounces.
WALK = [
    # Frame 0: right leg forward, left leg back — wide stride
    """
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    .....Lrrrrrrrrl.........
    ....LrRRrrrrRRrl........
    ....LrrrrrrrrrrrL.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......cccccccccc........
    ......gg......gg........
    .....gg........gg.......
    .....gg........gg.......
    .....gg........gg.......
    .....GG........GG.......
    .....dd........dd.......
    .....dD........Dd.......
    """,
    # Frame 1: passing — legs together, body up 1px (neck gone)
    """
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    .....Lrrrrrrrrl.........
    ....LrRRrrrrRRrl........
    ....LrrrrrrrrrrrL.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......cccccccccc........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......GG....GG.........
    .......dd....dd.........
    .......dD....Dd.........
    ........................
    """,
    # Frame 2: left leg forward, right leg back — narrow stride
    """
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    .....Lrrrrrrrrl.........
    ....LrRRrrrrRRrl........
    ....LrrrrrrrrrrrL.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......cccccccccc........
    .......gg....gg.........
    ........gg..gg..........
    ........gg..gg..........
    ........gg..gg..........
    ........GG..GG..........
    ........dd..dd..........
    ........Dd..dD..........
    """,
    # Frame 3: left leg forward, right back — wide stride (mirror of 0)
    """
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    .....Lrrrrrrrrl.........
    ....LrRRrrrrRRrl........
    ....LrrrrrrrrrrrL.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......cccccccccc........
    .......gg......gg.......
    ........gg......gg......
    ........gg......gg......
    ........gg......gg......
    ........GG......GG......
    ........dd......dd......
    ........Dd......dD......
    """,
    # Frame 4: passing — legs together, body up 1px (same as frame 1)
    """
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    .....Lrrrrrrrrl.........
    ....LrRRrrrrRRrl........
    ....LrrrrrrrrrrrL.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......cccccccccc........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......GG....GG.........
    .......dd....dd.........
    .......dD....Dd.........
    ........................
    """,
    # Frame 5: right leg forward — moderate stride
    """
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    .....Lrrrrrrrrl.........
    ....LrRRrrrrRRrl........
    ....LrrrrrrrrrrrL.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......cccccccccc........
    .......gg....gg.........
    ......gg......gg........
    ......gg......gg........
    ......gg......gg........
    ......GG......GG........
    ......dd......dd........
    ......dD......Dd........
    """,
]


# 2-frame jump. Frame 0 = ascending (compact), frame 1 = descending (extended).
JUMP = [
    # Frame 0: ascending — shorter robe, legs tucked closer
    """
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    .....Lrrrrrrrrl.........
    ....LrRRrrrrRRrl........
    ....LrrrrrrrrrrrL.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......ccrrrrrrcc........
    .......gggggggg.........
    .......gg....gg.........
    .......gg....gg.........
    .......GG....GG.........
    .......dd....dd.........
    .......dD....Dd.........
    """,
    # Frame 1: descending — fully extended, same as idle neutral
    """
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    .....Lrrrrrrrrl.........
    ....LrRRrrrrRRrl........
    ....LrrrrrrrrrrrL.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......cccccccccc........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......gg....gg.........
    .......GG....GG.........
    .......dd....dd.........
    .......dD....Dd.........
    """,
]

# 2-frame wall slide. Body pressed against wall (left side since MIRROR=True).
# Arms reach up, legs together, sliding down.
WALL_SLIDE = [
    # Frame 0: pressed against wall
    """
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    ....LLrrrrrrrrl.........
    ...LLrRRrrrrRRrl........
    ...LLrrrrrrrrrrrL.......
    ....Lrrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......cccccccccc........
    .......gg..gg...........
    .......gg..gg...........
    .......gg..gg...........
    .......gg..gg...........
    .......GG..GG...........
    .......dd..dd...........
    .......dD..Dd...........
    """,
    # Frame 1: slight arm shift
    """
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    ...LLLrrrrrrrrl.........
    ...LLrRRrrrrRRrl........
    ...LLrrrrrrrrrrrL.......
    ....Lrrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......cccccccccc........
    .......gg..gg...........
    .......gg..gg...........
    .......gg..gg...........
    .......gg..gg...........
    .......GG..GG...........
    .......dd..dd...........
    .......dD..Dd...........
    """,
]

# 2-frame wall jump. Explosive push-off from wall.
WALL_JUMP = [
    # Frame 0: coiled, about to push off
    """
    ........................
    ........................
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    ...LLrrrrrrrrl..........
    ..LLrRRrrrrRRrl.........
    ..LLrrrrrrrrrrrL........
    ...Lrrrrrrrrrrrr........
    ....bBbbbbbbbbBbl.......
    .....rrrrrrrrrr.l.......
    .....rrrrrrrrrr.........
    .....ccrrrrrrcc.........
    ......gggggggg..........
    ......gg....gg..........
    ......gg....gg..........
    ......GG....GG..........
    ......dd....dd..........
    ......dD....Dd..........
    ........................
    ........................
    ........................
    ........................
    """,
    # Frame 1: extended, pushing away
    """
    ........................
    .......hhhhhhhhh........
    ......hhhHHHHhhhh.......
    ......hhHHHHHHhhh.......
    ......hhHHHHHHhhh.......
    ......hLLLLLLLLhh.......
    ......hssssssssHh.......
    ......ssEssssEsHh.......
    ......sssssssssHh.......
    ......ssssmmssss........
    .......ssssssss.........
    ........ssss............
    .....Lrrrrrrrrl.........
    ....LrRRrrrrRRrl........
    ....LrrrrrrrrrrrL.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....rrrrrrrrrrrr.......
    .....bBbbbbbbbbBbl......
    ......rrrrrrrrrr.l......
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......rrrrrrrrrr........
    ......cccccccccc........
    ......gg......gg........
    .....gg........gg.......
    .....gg........gg.......
    .....GG........GG.......
    .....dd........dd.......
    .....dD........Dd.......
    ........................
    """,
]

# fmt: on

ANIMATIONS = {
    "idle": IDLE,
    "walk": WALK,
    "jump": JUMP,
    "wall_slide": WALL_SLIDE,
    "wall_jump": WALL_JUMP,
}
