"""Ramon sprite definitions — idle animation.

24x32 pixels per frame. Balearic foner (slinger) — deeply tanned,
full-length white/cream robe (not a t-shirt!), white headband tied
around forehead, sling visible. Stocky, determined expression.

Palette key reference (from RAMON_PALETTE):
    . = transparent
    h/H = hair dark/highlight
    s/S/k = skin base/shadow/deep shadow
    e/E = eye white/pupil    B = thick eyebrow
    m = mouth/nose skin shadow
    r/R/c = robe base/highlight/shadow
    w/W = headband white/shadow
    L/l = sling strap base/highlight
    b/A = belt dark/darker
    g = leg skin
    d/D = sandal base/dark
    o = outline accent
"""

from tools.sprite_defs.palettes import RAMON_PALETTE

PALETTE = RAMON_PALETTE
WIDTH = 24
HEIGHT = 32

# fmt: off

IDLE = [
    # Frame 0: neutral stance
    """
    ........................
    ........................
    .......hhhhhhhh.........
    ......hhhHHHHhhh........
    ......hhHHHHHHhh........
    ......hwwwwwwwwh........
    ......wsssssssw.........
    ......sBessBes..........
    ......seEsseEs..........
    ......ssssssss..........
    .......ssmms............
    .......ssssss...........
    ........sss.............
    ......rrrrrrrr..........
    .....rRrrrrrrrl.........
    .....rRrrrrrrrl.........
    .....rrrrrrrrrl.........
    .....rrrrrrrrrr.........
    .....rrrrrrrrrr.........
    .....rcrrrrrrrc.........
    .....rcrrrrrrrc.........
    ......rrrrrrrr..........
    ......rrrrrrrr..........
    ......rrrrrrrr..........
    ......rrrr.rrrr.........
    .......gg...gg..........
    ......dddd.dddd.........
    ......dDDd.dDDd.........
    ........................
    ........................
    ........................
    ........................
    """,
    # Frame 1: breathing in — torso up 1px
    """
    ........................
    ........................
    .......hhhhhhhh.........
    ......hhhHHHHhhh........
    ......hhHHHHHHhh........
    ......hwwwwwwwwh........
    ......wsssssssw.........
    ......sBessBes..........
    ......seEsseEs..........
    ......ssssssss..........
    .......ssmms............
    .......ssssss...........
    ......rrrrrrrr..........
    .....rRrrrrrrrl.........
    .....rRrrrrrrrl.........
    .....rRrrrrrrrl.........
    .....rrrrrrrrrl.........
    .....rrrrrrrrrr.........
    .....rrrrrrrrrr.........
    .....rcrrrrrrrc.........
    .....rcrrrrrrrc.........
    ......rrrrrrrr..........
    ......rrrrrrrr..........
    ......rrrrrrrr..........
    ......rrrr.rrrr.........
    .......gg...gg..........
    ......dddd.dddd.........
    ......dDDd.dDDd.........
    ........................
    ........................
    ........................
    ........................
    """,
    # Frame 2: same as frame 0
    """
    ........................
    ........................
    .......hhhhhhhh.........
    ......hhhHHHHhhh........
    ......hhHHHHHHhh........
    ......hwwwwwwwwh........
    ......wsssssssw.........
    ......sBessBes..........
    ......seEsseEs..........
    ......ssssssss..........
    .......ssmms............
    .......ssssss...........
    ........sss.............
    ......rrrrrrrr..........
    .....rRrrrrrrrl.........
    .....rRrrrrrrrl.........
    .....rrrrrrrrrl.........
    .....rrrrrrrrrr.........
    .....rrrrrrrrrr.........
    .....rcrrrrrrrc.........
    .....rcrrrrrrrc.........
    ......rrrrrrrr..........
    ......rrrrrrrr..........
    ......rrrrrrrr..........
    ......rrrr.rrrr.........
    .......gg...gg..........
    ......dddd.dddd.........
    ......dDDd.dDDd.........
    ........................
    ........................
    ........................
    ........................
    """,
    # Frame 3: breathing out — shoulders drop 1px
    """
    ........................
    ........................
    .......hhhhhhhh.........
    ......hhhHHHHhhh........
    ......hhHHHHHHhh........
    ......hwwwwwwwwh........
    ......wsssssssw.........
    ......sBessBes..........
    ......seEsseEs..........
    ......ssssssss..........
    .......ssmms............
    .......ssssss...........
    ........sss.............
    ........sss.............
    ......rrrrrrrr..........
    .....rRrrrrrrrl.........
    .....rRrrrrrrrl.........
    .....rrrrrrrrrl.........
    .....rrrrrrrrrr.........
    .....rrrrrrrrrr.........
    .....rcrrrrrrrc.........
    ......rrrrrrrr..........
    ......rrrrrrrr..........
    ......rrrrrrrr..........
    ......rrrr.rrrr.........
    .......gg...gg..........
    ......dddd.dddd.........
    ......dDDd.dDDd.........
    ........................
    ........................
    ........................
    ........................
    """,
]

# fmt: on

ANIMATIONS = {
    "idle": IDLE,
}
