"""Rival Warrior sprite definitions — idle, walk animations.

16x24 pixels per frame. Bronze-age tribal warrior with hide armor
and a stone spear. Dark skin, headwrap, leather straps.
"""

from tools.sprite_defs.palettes import RIVAL_WARRIOR_PALETTE

PALETTE = RIVAL_WARRIOR_PALETTE
WIDTH = 24
HEIGHT = 36

# fmt: off

IDLE = [
    # Frame 0: standing with spear
    """
    ......ww........
    ......ww........
    ....hhhhhh......
    ...hhHHHhhh.....
    ...hssssshh.....
    ...seEsseEs.....
    ...ssssssss.....
    ....ssssss......
    ...laaaaaal.....
    ..llAaaaaAll....
    ..laaaaaaaaal...
    ...aaaaaaaaa....
    ...aaaaaaaaa....
    ...llaaaaaall...
    ....ssssssss....
    .....gggggg.....
    .....gg..gg.....
    .....gg..gg.....
    .....gg..gg.....
    .....GG..GG.....
    .....ff..ff.....
    .....ff..ff.....
    ................
    ................
    """,
    # Frame 1: slight shift
    """
    ......ww........
    ......ww........
    ....hhhhhh......
    ...hhHHHhhh.....
    ...hssssshh.....
    ...seEsseEs.....
    ...ssssssss.....
    ....ssssss......
    ...laaaaaal.....
    ..llAaaaaAll....
    ..laaaaaaaaal...
    ...aaaaaaaaa....
    ...aaaaaaaaa....
    ...aaaaaaaaa....
    ...llaaaaaall...
    ....ssssssss....
    .....gggggg.....
    .....gg..gg.....
    .....gg..gg.....
    .....GG..GG.....
    .....ff..ff.....
    .....ff..ff.....
    ................
    ................
    """,
]

WALK = [
    # Frame 0: right leg forward
    """
    ......ww........
    ......ww........
    ....hhhhhh......
    ...hhHHHhhh.....
    ...hssssshh.....
    ...seEsseEs.....
    ...ssssssss.....
    ....ssssss......
    ...laaaaaal.....
    ..llAaaaaAll....
    ..laaaaaaaaal...
    ...aaaaaaaaa....
    ...aaaaaaaaa....
    ...llaaaaaall...
    ....ssssssss....
    .....gggggg.....
    ....gg....gg....
    ....gg....gg....
    ....gg....gg....
    ....GG....GG....
    ....ff....ff....
    ....ff....ff....
    ................
    ................
    """,
    # Frame 1: passing — body up 1px
    """
    ................
    ......ww........
    ......ww........
    ....hhhhhh......
    ...hhHHHhhh.....
    ...hssssshh.....
    ...seEsseEs.....
    ...ssssssss.....
    ....ssssss......
    ...laaaaaal.....
    ..llAaaaaAll....
    ..laaaaaaaaal...
    ...aaaaaaaaa....
    ...aaaaaaaaa....
    ...llaaaaaall...
    ....ssssssss....
    .....gggggg.....
    .....gg..gg.....
    .....gg..gg.....
    .....GG..GG.....
    .....ff..ff.....
    .....ff..ff.....
    ................
    ................
    """,
    # Frame 2: left leg forward
    """
    ......ww........
    ......ww........
    ....hhhhhh......
    ...hhHHHhhh.....
    ...hssssshh.....
    ...seEsseEs.....
    ...ssssssss.....
    ....ssssss......
    ...laaaaaal.....
    ..llAaaaaAll....
    ..laaaaaaaaal...
    ...aaaaaaaaa....
    ...aaaaaaaaa....
    ...llaaaaaall...
    ....ssssssss....
    .....gggggg.....
    ......gg.gg.....
    ......gg.gg.....
    ......gg.gg.....
    ......GG.GG.....
    ......ff.ff.....
    ......ff.ff.....
    ................
    ................
    """,
    # Frame 3: passing — body up 1px
    """
    ................
    ......ww........
    ......ww........
    ....hhhhhh......
    ...hhHHHhhh.....
    ...hssssshh.....
    ...seEsseEs.....
    ...ssssssss.....
    ....ssssss......
    ...laaaaaal.....
    ..llAaaaaAll....
    ..laaaaaaaaal...
    ...aaaaaaaaa....
    ...aaaaaaaaa....
    ...aaaaaaaaa....
    ...llaaaaaall...
    ....ssssssss....
    .....gg..gg.....
    .....gg..gg.....
    .....GG..GG.....
    .....ff..ff.....
    .....ff..ff.....
    ................
    ................
    """,
]

# fmt: on

ANIMATIONS = {
    "idle": IDLE,
    "walk": WALK,
}
