"""Stone Guardian sprite definitions — idle, walk animations.

24x32 pixels per frame. A heavy golem made of stone blocks with
glowing green eyes and mossy patches. Slow and imposing.
"""

from tools.sprite_defs.palettes import STONE_GUARDIAN_PALETTE

PALETTE = STONE_GUARDIAN_PALETTE
WIDTH = 36
HEIGHT = 48

# fmt: off

IDLE = [
    # Frame 0: standing tall
    """
    ........................
    ........................
    .......dddddddd........
    ......ddsSSSSsdd........
    .....ddSSSSSSSSdd.......
    .....dSSSSSSSSSSd.......
    .....dSSeESSeSESd.......
    .....dSSSSSSSSSSd.......
    .....ddsSSSSssdd........
    ......ddddddddd.........
    .......ddsssdd..........
    ......DDssssssDD........
    .....DDssSSSSssDd.......
    ....DDssSSSSSSSsDd......
    ....DssSSSSSSSSSdD......
    ....DssSSSSSSSSSdD......
    ....DDssSSSSSSssDd......
    .....DDssSSSssDD........
    .....mdddddddddm.......
    .....DDssSSssDDm........
    ......DssSSSsDm.........
    ......DssSSSsDm.........
    ......DssSSSsDd.........
    .......dsSSsd...........
    .......dsssssd..........
    ......DDdd.DDdd.........
    .....DDdd...DDdd........
    .....Ddd.....Ddd........
    .....ddd.....ddd........
    .....DDD.....DDD........
    ........................
    ........................
    """,
    # Frame 1: slight lean forward
    """
    ........................
    ........................
    .......dddddddd........
    ......ddsSSSSsdd........
    .....ddSSSSSSSSdd.......
    .....dSSSSSSSSSSd.......
    .....dSSEeSSEeSSd.......
    .....dSSSSSSSSSSd.......
    .....ddsSSSSssdd........
    ......ddddddddd.........
    .......ddsssdd..........
    ......DDssssssDD........
    .....DDssSSSSssDd.......
    ....DDssSSSSSSSsDd......
    ....DssSSSSSSSSSdD......
    ....DssSSSSSSSSSdD......
    ....DDssSSSSSSssDd......
    .....DDssSSSssDD........
    .....mdddddddddm.......
    .....DDssSSssDDm........
    ......DssSSSsDm.........
    ......DssSSSsDm.........
    ......DssSSSsDd.........
    .......dsSSsd...........
    .......dsssssd..........
    ......DDdd.DDdd.........
    .....DDdd...DDdd........
    .....Ddd.....Ddd........
    .....ddd.....ddd........
    .....DDD.....DDD........
    ........................
    ........................
    """,
]

WALK = [
    # Frame 0: right foot forward
    """
    ........................
    ........................
    .......dddddddd........
    ......ddsSSSSsdd........
    .....ddSSSSSSSSdd.......
    .....dSSSSSSSSSSd.......
    .....dSSeESSeSESd.......
    .....dSSSSSSSSSSd.......
    .....ddsSSSSssdd........
    ......ddddddddd.........
    .......ddsssdd..........
    ......DDssssssDD........
    .....DDssSSSSssDd.......
    ....DDssSSSSSSSsDd......
    ....DssSSSSSSSSSdD......
    ....DssSSSSSSSSSdD......
    ....DDssSSSSSSssDd......
    .....DDssSSSssDD........
    .....mdddddddddm.......
    .....DDssSSssDDm........
    ......DssSSSsDm.........
    ......DssSSSsDd.........
    .......dsSSsd...........
    .......dsssssd..........
    .....DDdd...DDdd........
    ....DDdd.....DDdd.......
    ....Ddd.......Ddd.......
    ....ddd.......ddd.......
    ....DDD.......DDD.......
    ........................
    ........................
    ........................
    """,
    # Frame 1: passing
    """
    ........................
    ........................
    ........................
    .......dddddddd........
    ......ddsSSSSsdd........
    .....ddSSSSSSSSdd.......
    .....dSSSSSSSSSSd.......
    .....dSSEeSSEeSSd.......
    .....dSSSSSSSSSSd.......
    .....ddsSSSSssdd........
    ......ddddddddd.........
    .......ddsssdd..........
    ......DDssssssDD........
    .....DDssSSSSssDd.......
    ....DDssSSSSSSSsDd......
    ....DssSSSSSSSSSdD......
    ....DssSSSSSSSSSdD......
    ....DDssSSSSSSssDd......
    .....DDssSSSssDD........
    .....mdddddddddm.......
    .....DDssSSssDDm........
    ......DssSSSsDm.........
    ......DssSSSsDd.........
    .......dsSSsd...........
    .......dsssssd..........
    ......DDdd.DDdd.........
    .....DDdd...DDdd........
    .....Ddd.....Ddd........
    .....ddd.....ddd........
    .....DDD.....DDD........
    ........................
    ........................
    """,
    # Frame 2: left foot forward
    """
    ........................
    ........................
    .......dddddddd........
    ......ddsSSSSsdd........
    .....ddSSSSSSSSdd.......
    .....dSSSSSSSSSSd.......
    .....dSSeESSeSESd.......
    .....dSSSSSSSSSSd.......
    .....ddsSSSSssdd........
    ......ddddddddd.........
    .......ddsssdd..........
    ......DDssssssDD........
    .....DDssSSSSssDd.......
    ....DDssSSSSSSSsDd......
    ....DssSSSSSSSSSdD......
    ....DssSSSSSSSSSdD......
    ....DDssSSSSSSssDd......
    .....DDssSSSssDD........
    .....mdddddddddm.......
    .....DDssSSssDDm........
    ......DssSSSsDm.........
    ......DssSSSsDd.........
    .......dsSSsd...........
    .......dsssssd..........
    ......DDdd...DDdd.......
    .......DDdd...DDdd......
    .......Ddd.....Ddd......
    .......ddd.....ddd......
    .......DDD.....DDD......
    ........................
    ........................
    ........................
    """,
]

# fmt: on

ANIMATIONS = {
    "idle": IDLE,
    "walk": WALK,
}
